### ISSUE TITLE
Mulighed for at definere profil brugt til minimap visning

### ISSUE THREAD

**Issue by daemonoropsis** [danielarnason/skolerute#1]
Fedt modul Daniel :)

Vil det være muligt at udvide det så man kan pege på en specifik sps profil til at bruge i kortet i stedet for default profilen så man kunne smide de temaer man havde lyst til skulle være synlige i den.

Bare til visuel visning. Jeg tænker mange vil være interesseret i at vise fx skoledistrikter og alle skole punkterne og flere har sikkert nogle 'Farlige skoleveje' agtige temaer man gerne vil se om krydser ruten.

I så fald vil det nok måske også være interessant hvis man kan hive signaturen med ind også da man jo så kunne vise hvad som helst.

**Comment by danielarnason** [comment]
Mange tak :)
Jeg har tænkt på det med profilen, men hvis jeg har forstået det hele rigtigt, så gør det det meget sværere at installere modulet, hvis man skal tilføje den mulighed. Men det er på min liste over ting, så jeg kommer nok til at kigge på det ved lejlighed.

Jeg har lige lavet et andet issue, hvad angår ekstra temaer ved start :) Se #2
